# Generated by Django 4.2.1 on 2023-05-31 01:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Helloworld', '0002_book_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='book',
            name='cover_page',
            field=models.ImageField(blank=True, null=True, upload_to='book_covers/'),
        ),
    ]
